_wandb:
    value:
        cli_version: 0.25.1
        e:
            fi0uu5xue4mpvvonkbw3e75rulqwsx0z:
                args:
                    - config/train_gpt2.py
                codePath: train_linesearch.py
                codePathLocal: train_linesearch.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "14687412224"
                        used: "10157494272"
                email: chongwei.cc@gmail.com
                executable: /users/9/chen8596/miniconda3/envs/nanogpt/bin/python3.9
                git:
                    commit: 38ba19945ca1f9ea5cf685a3af6170ff34fb79ca
                    remote: git@github.com:chongwei730/nanoGPT.git
                gpu: NVIDIA A40
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-e877c8ca-76bd-e123-1635-50e472f0f96a
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-304890a8-11ba-683e-44b7-e088609edb54
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-0a76f26b-b37f-a8c5-7bfb-74b3d57c3cf4
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-2b39551e-76c7-b237-001c-06c1b290f254
                host: agc01
                memory:
                    total: "540466794496"
                os: Linux-4.18.0-553.104.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /users/9/chen8596/nanoGPT/train_linesearch.py
                python: CPython 3.9.23
                root: /users/9/chen8596/nanoGPT
                slurm:
                    job_id: "5325662"
                startedAt: "2026-03-29T05:01:59.582199Z"
                writerId: fi0uu5xue4mpvvonkbw3e75rulqwsx0z
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.9.23
            "5": 0.25.1
            "8":
                - 2
            "12": 0.25.1
            "13": linux-x86_64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 12
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 1024
compile:
    value: true
dataset:
    value: openwebtext
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0
dtype:
    value: bfloat16
eval_interval:
    value: 1000
eval_iters:
    value: 200
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 40
init_from:
    value: scratch
learning_rate:
    value: 1e-06
log_interval:
    value: 10
lr_decay_iters:
    value: 600000
max_iters:
    value: 600000
min_lr:
    value: 6e-05
n_embd:
    value: 768
n_head:
    value: 12
n_layer:
    value: 12
out_dir:
    value: out
wandb_log:
    value: true
wandb_project:
    value: owt
wandb_run_name:
    value: gpt2-124M
warmup_iters:
    value: 2000
weight_decay:
    value: 0.1
